spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/backend_boilerplate}
    username: ${DB_USERNAME:backend}
    password: ${DB_PASSWORD:backend}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

jwt:
  secret: ${JWT_SECRET:CHANGE_ME}
  access-token-exp-minutes: ${JWT_ACCESS_MINUTES:60}
  refresh-token-exp-days: ${JWT_REFRESH_DAYS:14}
